import { GoBoard } from '../src/core/GoBoard';
import { MoveInsights } from '../src/ai/MoveInsights';
import { BoardSize, Color, Move } from '../src/types/go';
import { CONCEPTS, CONCEPT_ORDER } from '../src/data/concepts';
import { check, equal, suite } from './harness';
import { place } from './board.test';

/** Plays a move and returns the insights it produces. */
function insightsFor(
  diagram: string,
  x: number,
  y: number,
  color: Color,
  moveNumber = 5,
  size: BoardSize = 9
): { ids: string[]; byId: Map<string, { severity: string; detail: string; title: string }> } {
  const board = new GoBoard(size);
  place(board, diagram, color);

  const move: Move = { x, y, color };
  const pre = MoveInsights.capture(board, move);
  const res = board.playMove(x, y, color);
  if (!res.success) throw new Error(`move rejected: ${res.reason}`);

  const list = MoveInsights.analyze(
    board,
    pre,
    move,
    moveNumber,
    size,
    res.move?.captured?.length ?? 0
  );

  return {
    ids: list.map(i => i.id),
    byId: new Map(list.map(i => [i.id, { severity: i.severity, detail: i.detail, title: i.title }]))
  };
}

const EMPTY9 = `
  .........
  .........
  .........
  .........
  .........
  .........
  .........
  .........
  .........`;

export function runInsightTests(): void {
  suite('capture is reported with the real stone count', () => {
    // White stone in the corner with a single liberty at (0,1).
    const r = insightsFor(
      `
      OX.......
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .........`,
      0, 1, 'black'
    );
    check('capture detected', r.ids.includes('capture'), r.ids.join(','));
    check('count is in the text', r.byId.get('capture')!.title.includes('1'), r.byId.get('capture')!.title);
  });

  suite('self-atari is flagged as critical', () => {
    // Black at (0,0) would touch a white stone and keep only one liberty.
    const r = insightsFor(
      `
      .O.......
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .........`,
      0, 0, 'black'
    );
    check('self-atari detected', r.ids.includes('self-atari'), r.ids.join(','));
    equal('severity is critical', r.byId.get('self-atari')!.severity, 'critical');
  });

  suite('a safe move is not called self-atari', () => {
    const r = insightsFor(EMPTY9, 4, 4, 'black');
    check('no false self-atari on an empty board', !r.ids.includes('self-atari'), r.ids.join(','));
  });

  suite('ignoring an atari is reported with the group size', () => {
    // Black pair at the top has exactly one liberty, at (2,0).
    const diagram = `
      XX.......
      OO.......
      .........
      .........
      .........
      .........
      .........
      .........
      .........`;
    const r = insightsFor(diagram, 8, 8, 'black');
    check('atari-ignored detected', r.ids.includes('atari-ignored'), r.ids.join(','));
    const info = r.byId.get('atari-ignored')!;
    equal('two stones at risk is critical', info.severity, 'critical');
    check('the group size appears', info.title.includes('2'), info.title);
    check('the rescue point is named', info.detail.includes('C9'), info.detail);
  });

  suite('rescuing the same group reports a save instead', () => {
    const diagram = `
      XX.......
      OO.......
      .........
      .........
      .........
      .........
      .........
      .........
      .........`;
    const r = insightsFor(diagram, 2, 0, 'black');
    check('saved-group detected', r.ids.includes('saved-group'), r.ids.join(','));
    check('no longer reported as ignored', !r.ids.includes('atari-ignored'), r.ids.join(','));
  });

  suite('putting the opponent in atari is reported', () => {
    // White at (1,1) has liberties at (2,1) and (1,2); black takes one.
    const diagram = `
      .X.......
      XO.......
      .........
      .........
      .........
      .........
      .........
      .........
      .........`;
    const r = insightsFor(diagram, 2, 1, 'black');
    check('gives-atari detected', r.ids.includes('gives-atari'), r.ids.join(','));
    equal('it is good news', r.byId.get('gives-atari')!.severity, 'good');
  });

  suite('connecting two groups is recognised', () => {
    const diagram = `
      X.X......
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .........`;
    const r = insightsFor(diagram, 1, 0, 'black');
    check('connects detected', r.ids.includes('connects'), r.ids.join(','));
    check('says how many groups', r.byId.get('connects')!.title.includes('2'), r.byId.get('connects')!.title);
  });

  suite('cutting two opponent groups is recognised', () => {
    const diagram = `
      O.O......
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .........`;
    const r = insightsFor(diagram, 1, 0, 'black');
    check('cut detected', r.ids.includes('cut'), r.ids.join(','));
  });

  suite('filling your own eye is called out', () => {
    const diagram = `
      .X.......
      X.X......
      .X.......
      .........
      .........
      .........
      .........
      .........
      .........`;
    const r = insightsFor(diagram, 1, 1, 'black');
    check('filled-own-eye detected', r.ids.includes('filled-own-eye'), r.ids.join(','));
    equal('severity is critical', r.byId.get('filled-own-eye')!.severity, 'critical');
  });

  suite('board position advice depends on the line', () => {
    const early = insightsFor(EMPTY9, 0, 4, 'black', 3);
    check('first line flagged early', early.ids.includes('first-line-early'), early.ids.join(','));

    const good = insightsFor(EMPTY9, 2, 2, 'black', 3);
    check('third line praised', good.ids.includes('good-line'), good.ids.join(','));
    check('corner opening praised', good.ids.includes('corner-opening'), good.ids.join(','));

    // Late in the game the edge is normal play, so no warning.
    const late = insightsFor(EMPTY9, 0, 4, 'black', 60);
    check('no edge warning late in the game', !late.ids.includes('first-line-early'), late.ids.join(','));
  });

  suite('empty triangle is recognised', () => {
    const diagram = `
      XX.......
      X........
      .........
      .........
      .........
      .........
      .........
      .........
      .........`;
    // Playing (1,1) completes the square, which is not a triangle; play a shape
    // that leaves the diagonal empty instead.
    const r = insightsFor(
      `
      .X.......
      X........
      .........
      .........
      .........
      .........
      .........
      .........
      .........`,
      0, 0, 'black', 40
    );
    void diagram;
    check('empty triangle detected', r.ids.includes('empty-triangle'), r.ids.join(','));
  });

  suite('passing gets its own note', () => {
    const board = new GoBoard(9);
    const move: Move = { x: -1, y: -1, color: 'black', pass: true };
    const pre = MoveInsights.capture(board, move);
    board.pass('black');
    const list = MoveInsights.analyze(board, pre, move, 30, 9, 0);
    equal('one insight for a pass', list.length, 1);
    equal('it points at the pass concept', list[0].concept, 'passar');
  });

  suite('candidate descriptions state what the move achieves', () => {
    const board = new GoBoard(9);
    place(board, `
      OX.......
      .........
      .........
      .........
      .........
      .........
      .........
      .........
      .........`, 'black');
    const capturing = MoveInsights.describeCandidate(board, { x: 0, y: 1 }, 'black', 9);
    check('capture is described as a capture', capturing.includes('captura'), capturing);

    const empty = new GoBoard(9);
    const territory = MoveInsights.describeCandidate(empty, { x: 2, y: 2 }, 'black', 9);
    check('a quiet move still gets a reason', territory.length > 0, territory);
    check('no percentages leak into the wording', !territory.includes('%'), territory);
  });

  suite('every insight points at a concept that exists', () => {
    const samples = [
      insightsFor(EMPTY9, 2, 2, 'black', 3),
      insightsFor(EMPTY9, 0, 0, 'black', 3),
      insightsFor(EMPTY9, 4, 4, 'black', 40)
    ];
    void samples;

    // The glossary must cover every concept id and be ordered completely.
    const ids = Object.keys(CONCEPTS);
    equal('glossary order lists every concept', CONCEPT_ORDER.length, ids.length);
    for (const id of CONCEPT_ORDER) {
      const c = CONCEPTS[id];
      check(`${id} has a name`, !!c && c.name.length > 0);
      check(`${id} has an explanation`, !!c && c.explanation.length > 40);
      check(`${id} has practical advice`, !!c && c.practice.length > 20);
    }
  });
}
