import { GoBoard } from '../src/core/GoBoard';
import { GoScoring } from '../src/core/GoScoring';
import { check, equal, suite } from './harness';
import { place } from './board.test';

export function runScoringTests(): void {
  suite('Benson: a two-eye group is unconditionally alive', () => {
    const b = new GoBoard(9);
    place(b, `
      .X.X.....
      XXXX.....
      .........
      .........
      .........
      .........
      .........
      .........
      .........`);
    const alive = GoScoring.bensonPassAlive(b, 'black');
    check('pass-alive set is not empty', alive.size > 0, `size=${alive.size}`);
    equal('the group is never marked dead', GoScoring.autoDetectDeadStones(b).size, 0);
  });

  suite('an enclosed one-eye group is dead', () => {
    const b = new GoBoard(9);
    place(b, `
      OOOOO....
      OXXXO....
      OX.XO....
      OXXXO....
      OOOOO....
      .........
      .........
      .........
      .........`);
    const dead = GoScoring.autoDetectDeadStones(b);
    equal('all eight black stones are dead', dead.size, 8);
    check('the surrounding white wall survives', !dead.has('0,0'));
  });

  suite('an enclosed two-eye group lives', () => {
    const b = new GoBoard(9);
    place(b, `
      OOOOOOO..
      OXXXXXO..
      OX.X.XO..
      OXXXXXO..
      OOOOOOO..
      .........
      .........
      .........
      .........`);
    equal('nothing is marked dead', GoScoring.autoDetectDeadStones(b).size, 0);
  });

  suite('a lone invader inside enemy territory is dead', () => {
    const b = new GoBoard(9);
    place(b, `
      OOOOO....
      O.X.O....
      OOOOO....
      .........
      .........
      .........
      .........
      .........
      .........`);
    check('the invader is marked dead', GoScoring.autoDetectDeadStones(b).has('2,1'));
  });

  suite('open groups on a mostly empty board are never dead', () => {
    const b = new GoBoard(9);
    place(b, `
      XX.......
      XX.......
      .........
      .........
      .........
      .........
      .........
      .......OO
      .......OO`);
    equal('no false positives', GoScoring.autoDetectDeadStones(b).size, 0);
  });

  suite('territory counting on a split board', () => {
    const b = new GoBoard(9);
    place(b, `
      ...XO....
      ...XO....
      ...XO....
      ...XO....
      ...XO....
      ...XO....
      ...XO....
      ...XO....
      ...XO....`);
    const jp = GoScoring.calculateScore(b, new Set(), 'japanese', 6.5);
    equal('black territory', jp.blackTerritory, 27);
    equal('white territory', jp.whiteTerritory, 36);
    equal('white wins on komi', jp.winner, 'white' as const);

    const cn = GoScoring.calculateScore(b, new Set(), 'chinese', 6.5);
    equal('chinese adds living stones for black', cn.blackTotal, 27 + 9);
    equal('chinese adds living stones for white', cn.whiteTotal, 36 + 9 + 6.5);
  });

  suite('dead stones become prisoners and free their territory', () => {
    const b = new GoBoard(9);
    place(b, `
      OOOOO....
      O.X.O....
      OOOOO....
      .........
      .........
      .........
      .........
      .........
      .........`);
    const alive = GoScoring.calculateScore(b, new Set(), 'japanese', 6.5);
    const dead = GoScoring.calculateScore(b, new Set(['2,1']), 'japanese', 6.5);

    // While the invader lives, the two points beside it are contested dame.
    equal('two dame become white territory', dead.whiteTerritory, alive.whiteTerritory + 2);
    equal('and the stone itself becomes a prisoner', dead.whiteTotal, alive.whiteTotal + 3);
  });

  suite('an empty board scores as a draw offset by komi', () => {
    const b = new GoBoard(9);
    const s = GoScoring.calculateScore(b, new Set(), 'japanese', 6.5);
    equal('no territory for black', s.blackTerritory, 0);
    equal('no territory for white', s.whiteTerritory, 0);
    equal('white leads by komi', s.whiteTotal, 6.5);
    equal('white is ahead', s.winner, 'white' as const);
  });
}
